### Listar todas as tarefas
GET http://localhost:8080/tasks
Accept: application/json

###

### Criar uma nova tarefa
POST http://localhost:8080/tasks
Content-Type: application/json
Accept: application/json

{
  "title": "Nova Tarefa",
  "description": "Descrição da nova tarefa"
}

###

### Atualizar uma tarefa existente
PUT http://localhost:8080/tasks/42
Content-Type: application/json
Accept: application/json

{
  "title": "Tarefa Atualizada denovo novo",
  "description": "Descrição atualizada",
  "status": "completed"
}

###

### Deletar uma tarefa
DELETE http://localhost:8080/tasks/46
Accept: application/json

###