services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: taskManagement
      POSTGRES_USER: viniciussantos
      POSTGRES_PASSWORD: PASSWORD123@
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  taskmanagement-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db-data: